@startuml
boundary SomeClient as "Some Client" order 5
participant ScoringApplicationService as "Scoring\nApplication\nService" order 10
participant ScoringDomainService as "Scoring\nDomain\nService" order 70
participant ApplicantClusterRepository as "Applicant\nCluster\nRepository" order 30
participant AgencyResultClusterRepository as "AgencyResult\nCluster\nRepository" order 40
participant MonthlyHouseholdBalanceClusterRespository as "Monthly\nHouseholdBalance\nCluster\nRespository" order 50
participant RealEstateFinancingClusterRepository as "RealEstate\nFinancing\nCluster\nRepository" order 60

SomeClient -> ScoringApplicationService: performPreScoring(applicationNumber)\nor\nperformMainScoring(applicationNumber)

ScoringApplicationService -> ScoringApplicationService: performAuthentication
ScoringApplicationService -> ScoringApplicationService: startTransaction
group Retrieve aggregates for all of the clusters
ScoringApplicationService -> ApplicantClusterRepository: findByScoringId(scoringId)
ApplicantClusterRepository --> ScoringApplicationService: ApplicantCluster
ScoringApplicationService -> AgencyResultClusterRepository: findByAgencyResultId(agencyResultId)
AgencyResultClusterRepository --> ScoringApplicationService: AgencyResultClusterRepository
ScoringApplicationService -> MonthlyHouseholdBalanceClusterRespository: findByScoringId(scoringId)
MonthlyHouseholdBalanceClusterRespository --> ScoringApplicationService: MonthlyHouseholdBalanceCluster
ScoringApplicationService -> RealEstateFinancingClusterRepository: findByScoringId(scoringId)
RealEstateFinancingClusterRepository -> ScoringApplicationService: RealEstateFinancingCluster
end

group Perform the actual scoring in the domain service
ScoringApplicationService -> ScoringDomainService: performScoring(applicantClusterAggregate,\n\t\t\t\tagencyResultClusterAggregate,\n\t\t\t\tmonthlyHouseholdBalanceAggregate,\n\t\t\t\trealEstateFinancingClusterAggregate)
ScoringDomainService --> ScoringApplicationService: ScoringColor
end

ScoringApplicationService -> ScoringApplicationService: commitTransaction
ScoringApplicationService --> SomeClient: ScoringColor
@enduml